name: Github Actions Demo
run-name: ${{github.actor}} is testing out Github Actions 💥

on:
  push:
    branches: -main
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-22
    steps:
      - name: Say Hello
        run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
